### ISSUE TITLE
pls bro haw 2 fix error link umm ,y my pc it's is windows vista paradise edishun and not work

### ISSUE THREAD

**Issue by Zenixa** [Debugtopia/GrowBase#1]
whats boolean??

**Comment by Debugtopia** [comment]
boolean used for growtopia tcp communication from client to server, enet requires boolean to function! No problem kind sir!

**Comment by Zenixa** [comment]
okkk bro me try on 64gb rams 19 vcpu serber wit centOS and it crash wtF! booleans memleak pls fix it im crying

**Comment by Debugtopia** [comment]
i fix sir! wait 38 seconds me call my coder vytenis kalaciovas
